### PR TITLE
Fixed theme load function to update update the a field is not set

### LINKED ISSUE #436: Reset JSON not working when there is only one customized component in the options
Steps to repro:
- In Admin panel, go to Apple News -> Customize JSON.
- Select a theme, modify a component JSON and save.
- If there other modified components, hitting the 'Reset JSON' will work as expected and return the component to it's original registered spec. If there are no other modified components, the customized JSON will return unaltered.

The reason for this is that the theme class [load](https://github.com/alleyinteractive/apple-news/blob/20231e4340ce7a010a63eca04ce73b4c99e184dd/includes/apple-exporter/class-theme.php#L1220) function is not updating the theme options when a field in the values parameter is empty. That field needs to be unset to remove it from the theme values. The json_template field being correctly removed from the theme settings by the component spec class [delete](https://github.com/alleyinteractive/apple-news/blob/dd00129b96ded48f71ec19a121460833b6454827/includes/apple-exporter/class-component-spec.php#L325) function.

### PR DESCRIPTION
**Pull request by dante-gutierrez**
- Checking if the value is set and if it is not, unset it from the theme values array.

Fixes #436

### CODE REVIEW

**Comment by dante-gutierrez** [comment]
Tests are passing locally for me. Let me know if there are changes needed.

**Comment by kevinfodness** [comment]
Hi @dante-gutierrez—

Thanks for the pull request. I see what you're doing, and I understand the problem that you're solving, but I'm concerned that by inverting the logic it's going to let in non-whitelisted options. I'll set up a test case to verify, and if I'm right, I'll come back with recommendations on how to fix.

**Comment by kevinfodness** [comment]
I've created a PR with an additional test that was failing before, and is now passing, with a fix in place that is a combination of your fix and the original code. Can you take a look and let me know if this solves for your use case:

https://github.com/alleyinteractive/apple-news/pull/439

**Comment by dante-gutierrez** [comment]
@kevinfodness, PR #439 fixes issue #436. Closing this PR now. 

Thanks!

**Comment by kevinfodness** [comment]
Great! I'll get that through code review on my side and it will be part of the next version. Thanks for identifying the issue and proposing a fix!

**Pull request closed without merging**
