### PR TITLE
Sets default meta values as arrays

### PR DESCRIPTION
**Pull request by msawicki**
This fixes an issue of an array to string conversion in `wp core wp-includes/rest-api/fields/class-wp-rest-meta-fields.php:425` when checking if a meta value has been updates or not. These values are handled as if they should be arrays so they should probably default as such.

We see this warning in automated tests and in our error logs pretty consistently with just updating articles. This should close this issue. https://github.com/alleyinteractive/apple-news/issues/963

### CODE REVIEW

**Comment by msawicki** [comment]
👋 Hey @attackant just wondering if you think this will get approved an in a future release? Thanks in advanced.

**Comment by attackant** [comment]
I looked into this a bit last week, however this PR causes other problems in our unit tests, so I'm not sure we've gotten to the bottom of this here. However, other more serious bugs have taken my focus, but I am planning to revisit this.

**Comment by attackant** [comment]
@msawicki Is this still an issue in the current version? In my dev environment I am not seeing this warning or notices. However, when I apply your suggested patch I do see new PHP notices when running unit tests.

**Comment by msawicki** [comment]
@attackant yes it is still happening. I can replicate this in the editor by updating a Section or changing any meta value and it happens on the `/wp-json/wp/v2/posts/<post_id>` request like it's mentioned in  https://github.com/alleyinteractive/apple-news/issues/963

The core issue seems to be if the meta value is going to be an array, it shouldn't be registered as a string default.

**Comment by msawicki** [comment]
I'm also seeing `doing_it_wrong` because these don't have a `type` defined?  I haven't looked into this too much. 
Screenshot 2024-03-12 at 6 53 46 AM

**Comment by msawicki** [comment]
Also note that I pushed a chance since those defaults are no longer strings, it fixes the `doing_it_wrong` notices. Not sure if that helps.

**Comment by msawicki** [comment]
~An alternative solution here. Setting the default to '{}' and keeping it as a string also seems to fix this and doesn't cause any of the doing it wrong warnings, or require defining the array schema. I'm afraid I just don't have a lot of context here but it appears that if `{}` is the default it gets json_decoded/encoded properly.~ I actually spoke too soon on this. I'm still seeing this Notice with that change.

**Pull request closed without merging**
