### PR TITLE
Update default value for items missing size attribute

### PR DESCRIPTION
**Pull request by ShashwatMittal**
Address https://github.com/alleyinteractive/apple-news/commit/828ad18918126b3f3cd03dd823a58870da4a8fe6#commitcomment-41032233

### CODE REVIEW

**Comment by kevinfodness** [comment]
This should be fixed in the in-development version 2.1.0. Can you check out `v2.1.0` and see if that fixes the issue for you?

**Comment by ShashwatMittal** [comment]
@kevinfodness Yes, this is fixed in v2.1.0. Though I would still recommend we have the size defined for this one as well. https://github.com/alleyinteractive/apple-news/blob/develop/admin/settings/class-admin-apple-settings-section-developer-tools.php#L43
Since it should match the same as https://github.com/alleyinteractive/apple-news/blob/develop/admin/settings/class-admin-apple-settings-section-api.php#L35

**Comment by ShashwatMittal** [comment]
I have updated the PR for the above suggestion. If not please go ahead and close the PR.
Thanks for the info.

**Comment by kevinfodness** [comment]
Works for me! I'm going to change the head branch to the `v2.1.0` feature and I'll get this merged after the checks pass. Thanks!

**Pull request merged**
