### PR TITLE
Add filter to API request meta

### PR DESCRIPTION
**Pull request by dashaluna**
You can specify a variety of API request meta before pushing to Apple News - [docs example](https://developer.apple.com/library/ios/documentation/General/Conceptual/News_API_Ref/CreateArticle.html#//apple_ref/doc/uid/TP40015409-CH14-SW11).

You can specify, for example, links -> sections, so that a post is published in the channel by default and also in the specified sections. Currently, there is no way to add custom meta to request.

Feel free to rename the filter name if required.

### CODE REVIEW

**Comment by dashaluna** [comment]
@bcampeau Hello! I was wondering when this will make to VIP? You'd like to start using this asap :) Please let me know. Thank you!

**Comment by bcampeau** [comment]
I've submitted this to them today.

On Fri, Feb 26, 2016 at 6:38 AM, Dasha Luna <notifications@github.com>
wrote:

> @bcampeau <https://github.com/bcampeau> Hello! I was wondering when this
> will make to VIP? You'd like to start using this asap :) Please let me
> know. Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alleyinteractive/apple-news/pull/84#issuecomment-189234372>
> .
>



-- 
Brad Campeau-Laurion
Partner, Alley Interactive
212-257-2154

**Comment by bcampeau** [comment]
VIP is putting this in their review queue. I'll let you know on timing.

**Comment by dashaluna** [comment]
Thank you! I'll keep an eye as well.

**Comment by dashaluna** [comment]
@bcampeau I've been checking on this - still nothing. It's been over a week now, I wonder if we could check with VIP what's going on with this? :)

**Comment by bcampeau** [comment]
They're very slow about plugin update sometimes. I've asked a couple times now, nothing yet.

**Comment by bcampeau** [comment]
I've been told "this week"

**Comment by dashaluna** [comment]
Thank you for checking!

**Comment by dashaluna** [comment]
Hurray.. they finally updated it!

**Pull request merged**
